# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Type',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=400)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=13)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('num_stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('num_reviews', models.IntegerField()),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=5)),
                ('picture_url', models.CharField(max_length=2083, null=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='POI_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Category_Type')),
                ('poi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.POI')),
            ],
        ),
    ]
