# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20161027_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='summary',
            field=models.CharField(max_length=5000),
        ),
    ]
