# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20161105_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi_type',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='poi_type',
            name='poi_id',
        ),
        migrations.AddField(
            model_name='poi',
            name='category',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_Type',
        ),
        migrations.DeleteModel(
            name='POI_Type',
        ),
    ]
