# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20161108_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='popularity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
