# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_poi_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='popularity',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
