# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20161108_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
