# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category_type', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('num_stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('num_reviews', models.IntegerField()),
                ('phone_number', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=5)),
                ('picture_url', models.CharField(max_length=2083)),
                ('summary', models.TextField()),
            ],
        ),
    ]
