# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Type',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('max_num_reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='POI_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pois.Category_Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='poi',
            name='category_type',
        ),
        migrations.AddField(
            model_name='poi_type',
            name='poi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pois.POI'),
        ),
    ]
