# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_auto_20161015_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_type',
            name='max_num_reviews',
        ),
    ]
