# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_remove_category_type_max_num_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi_type',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='poi_type',
            name='poi_id',
        ),
        migrations.DeleteModel(
            name='Category_Type',
        ),
        migrations.DeleteModel(
            name='POI_Type',
        ),
    ]
