# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0005_category_type_poi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='poi',
            name='picture_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
