# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0006_auto_20161018_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='picture_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
