# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0007_auto_20161018_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='poi',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
